export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnosterzakpink"

plugins=(
    git
    archlinux
    zsh-autosuggestions
    zsh-syntax-highlighting
)

export EDITOR="code"
export NAME_CONFIG_FASTFETCH="config"

source $ZSH/oh-my-zsh.sh

# Start
$HOME/.config/hypr/UserScripts/RandomFastfetchIcon.sh $NAME_CONFIG_FASTFETCH.jsonc

# Set-up FZF key bindings (CTRL R for fuzzy history finder)
source <(fzf --zsh)

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# Set-up icons for files/directories in terminal using lsd
alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

# Light
# alias orgbp="openrgb -p"

# Simpler
alias cd="z"

# Develop
# alias androidstart="hyprctl dispatch exec scrcpy"

# Fun
alias rain="$HOME/.config/hypr/UserScripts/RainbowText.sh"

clear-on-empty() {
    if [[ -z "$BUFFER" ]]; then
        zle clear-screen
    else
        zle accept-line
    fi
}

zle -N clear-on-empty
bindkey '^M' clear-on-empty
